FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache bash netcat-openbsd dos2unix

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
RUN npx prisma generate

COPY . .
RUN dos2unix docker/startup.sh && chmod +x docker/startup.sh

EXPOSE 3000

CMD ["bash", "docker/startup.sh"]